name: CI - Release Branch

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Linters
        run: npm install htmlhint stylelint stylelint-config-standard

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html"

      - name: Run Stylelint
        run: npx stylelint "**/*.css"
